// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// eskinIndexGather
NumericMatrix eskinIndexGather(NumericVector freqs, StringVector namesFreqs, StringVector datVar);
RcppExport SEXP _catDist_eskinIndexGather(SEXP freqsSEXP, SEXP namesFreqsSEXP, SEXP datVarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type freqs(freqsSEXP);
    Rcpp::traits::input_parameter< StringVector >::type namesFreqs(namesFreqsSEXP);
    Rcpp::traits::input_parameter< StringVector >::type datVar(datVarSEXP);
    rcpp_result_gen = Rcpp::wrap(eskinIndexGather(freqs, namesFreqs, datVar));
    return rcpp_result_gen;
END_RCPP
}
// inverseOccurenceGather
NumericMatrix inverseOccurenceGather(NumericMatrix distLookup, StringVector namesDistLookup, StringVector datVar);
RcppExport SEXP _catDist_inverseOccurenceGather(SEXP distLookupSEXP, SEXP namesDistLookupSEXP, SEXP datVarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type distLookup(distLookupSEXP);
    Rcpp::traits::input_parameter< StringVector >::type namesDistLookup(namesDistLookupSEXP);
    Rcpp::traits::input_parameter< StringVector >::type datVar(datVarSEXP);
    rcpp_result_gen = Rcpp::wrap(inverseOccurenceGather(distLookup, namesDistLookup, datVar));
    return rcpp_result_gen;
END_RCPP
}
// goodallIndexGather
NumericMatrix goodallIndexGather(NumericVector distLookup, StringVector namesDistLookup, StringVector datVar);
RcppExport SEXP _catDist_goodallIndexGather(SEXP distLookupSEXP, SEXP namesDistLookupSEXP, SEXP datVarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type distLookup(distLookupSEXP);
    Rcpp::traits::input_parameter< StringVector >::type namesDistLookup(namesDistLookupSEXP);
    Rcpp::traits::input_parameter< StringVector >::type datVar(datVarSEXP);
    rcpp_result_gen = Rcpp::wrap(goodallIndexGather(distLookup, namesDistLookup, datVar));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_catDist_eskinIndexGather", (DL_FUNC) &_catDist_eskinIndexGather, 3},
    {"_catDist_inverseOccurenceGather", (DL_FUNC) &_catDist_inverseOccurenceGather, 3},
    {"_catDist_goodallIndexGather", (DL_FUNC) &_catDist_goodallIndexGather, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_catDist(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
