# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eskinIndexGather <- function(freqs, namesFreqs, datVar) {
    .Call('_catDist_eskinIndexGather', PACKAGE = 'catDist', freqs, namesFreqs, datVar)
}

inverseOccurenceGather <- function(distLookup, namesDistLookup, datVar) {
    .Call('_catDist_inverseOccurenceGather', PACKAGE = 'catDist', distLookup, namesDistLookup, datVar)
}

goodallIndexGather <- function(distLookup, namesDistLookup, datVar) {
    .Call('_catDist_goodallIndexGather', PACKAGE = 'catDist', distLookup, namesDistLookup, datVar)
}

